{"name": "test number from history exist in list order", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "driver_with_order = (<selenium.webdriver.firefox.webdriver.WebDriver (session=\"b569e8ab-45c6-4bad-8290-c7ac148f0e2c\")>, '9999')\n\n    @pytest.fixture\n    def driver_with_two_orders(driver_with_order):\n        login_user, order_number = driver_with_order\n        home_page = HomePage(login_user)\n        home_page.open_page()\n>       home_page.create_new_order()\n\nconftest.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\home_page.py:89: in create_new_order\n    self.wait_on_off_load_animation()\npages\\home_page.py:82: in wait_on_off_load_animation\n    self.wait_element(HomePage.loading_animation)\npages\\base_page.py:22: in wait_element\n    WebDriverWait(self.driver, 10).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"b569e8ab-45c6-4bad-8290-c7ac148f0e2c\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x04621708>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "parameters": [{"name": "driver_factory", "value": "'Firefox'"}], "start": 1730191300737, "stop": 1730191300737, "uuid": "ab9647ac-58ea-4303-ae3b-e8cd5cc237e7", "historyId": "789df9cd50c1fded25a2c45e85200377", "testCaseId": "48701903e58a4ef914556a554e8dbe67", "fullName": "tests.test_order_list.TestOrderList#test_number_from_history_exist_in_list_order", "labels": [{"name": "suite", "value": "Test Order List"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestOrderList"}, {"name": "host", "value": "MM"}, {"name": "thread", "value": "2492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_list"}]}